# GitHub Actions Workflow for Transcriptor

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -e .[dev]
    
    - name: Lint with ruff
      run: |
        ruff check .
    
    - name: Run tests
      run: |
        pytest
    
    - name: Run UI tests
      run: |
        pytest tests/test_editor.py
    
    - name: Run pipeline tests
      run: |
        pytest tests/test_pipeline.py

  build:
    needs: test
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.13]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -e .[dev]
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed src/transcriptor/main.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: transcriptor-windows-${{ matrix.python-version }}
        path: dist/
    
    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
        draft: true
        prerelease: false